const actions = {
    SET_LOADING: 1,
    SET_OFF_LOADING: 17,
    AUTHENTICATE_ACTION: 2,
    LOGIN_ACTION: 3,
    LOGIN_FAILED: 4,
    REGISTER_ACTION: 5,
    LOGOUT_ACTION: 6,
    FORGET_PASS_ACTION: 7,
    AUTHENTICATE_FAILED: 8,
    WORKSPACE_ACTION: 9,
    SET_POST_ACTION: 10,
    GET_POST_LIST: 11,
    GET_SINGLE_POST: 12,
    POST_IDEA: 13,
    MESSAGE_ACTION: 14,
    ERROR_ACTION: 15,
    GET_POST_CATEGORIES: 16,
}

export default actions;